### ISSUE TITLE
[QRCodeWebLoader] 保存先フォルダの"参照"が OpenFileDialog になっている。

### ISSUE THREAD

**Issue by yukimochi** [Himakuma/VrChat#4]
フォルダ選択ダイアログには、ろくな実装がないのは同意します 🙃

ref. [こんなやつ](https://github.com/yukimochi/COM_Update_Manager/blob/master/COM-UM-WPFUI/MainWindow.xaml.cs#L64-L70)

**Comment by Himakuma** [comment]
CommonOpenFileDialogを使いたいですが、ライセンスが不明慮なのでいったん、
存在しないファイル名を初期で設定、ファイルのチェックをなしにして回避しました。

**Comment by Himakuma** [comment]
下記へ移行
https://github.com/Himakuma/QRCodeWebLoader/issues/1
